name: Check Backend

on:
  # I want to run this workflow manually too
  workflow_dispatch:

  # on every pull request to develop or master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - "src/**"
      - "server.js"
      - "i18n/**"
      - "tests/**"

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Create .env.test file
        run: |
          rm -f .env.test
          touch .env.test
          echo "PORT=${{ secrets.PORT }}" >> .env.test
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test

      - name: Install dependencies
        run: npm install

      - name: Generate types
        run: npm run once-typesafe-i18n

      - name: Check eslint
        run: npm run lint

      - name: Run tests
        run: npm run test

      # - name: Run tests
      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     test-script: npm run test
